config/routes.rb
require 'api_constraints'

DeviseApiRailsWorking::Application.routes.draw do
  get 'feedbacks/profile'

  # ------- Admin Routes Start -------
  match '/admin/feedback_index', :controller => 'admin', :action => 'feedback_index', via: [:get, :post]
  match '/admin/user_index', :controller => 'admin', :action => 'user_index', via: [:get, :post]
  match '/admin/agency_index', :controller => 'admin', :action => 'agency_index', via: [:get, :post]
  match '/admin/assign_agency', :controller => 'admin', :action => 'assign_agency', via: [:get, :post]
  match '/admin/delete_feedback', :controller => 'admin', :action => 'delete_feedback', via: [:get, :post]
  match '/admin/delete_user', :controller => 'admin', :action => 'delete_user', via: [:get, :post]
  match '/admin/assign_abuse_status', :controller => 'admin', :action => 'assign_abuse_status', via: [:get, :post]
  match '/admin/add_agency', :controller => 'admin', :action => 'add_agency', via: [:get, :post]
  match '/admin/suspend_user', :controller => 'admin', :action => 'suspend_user', via: [:get, :post]
  match '/admin/unsuspend_user', :controller => 'admin', :action => 'unsuspend_user', via: [:get, :post]
  match '/admin/edit_agency', :controller => 'admin', :action => 'edit_agency', via: [:get, :post]
  match '/admin/edit_agency2', :controller => 'admin', :action => 'edit_agency2', via: [:get, :post]
  # ------- Admin Routes End -------


  # ------- Feedbacks Routes Start -------
  match '/feedbacks/index', :controller => 'feedbacks', :action => 'index', via: [:get, :post]
  match '/feedbacks/search', :controller => 'feedbacks', :action => 'search', via: [:get, :post]
  match '/feedbacks/show', :controller => 'feedbacks', :action => 'show', via: [:get, :post]
  match '/feedbacks/create_vote', :controller => 'feedbacks', :action => 'create_vote', via: [:get, :post]
  match '/feedbacks/create_comment', :controller => 'feedbacks', :action => 'create_comment', via: [:get, :post]
  match '/feedbacks/unvote', :controller => 'feedbacks', :action => 'unvote', via: [:post, :delete]
  match '/feedbacks/my_feedbacks', :controller => 'feedbacks', :action => 'my_feedbacks', via: [:get, :post]
  match '/feedbacks/report_abuse', :controller => 'feedbacks', :action => 'report_abuse', via: [:get, :post]
  match '/feedbacks/marked_as_resolved', :controller => 'feedbacks', :action => 'marked_as_resolved', via: [:get, :post]
  match '/feedbacks/assign_progress_status', :controller => 'feedbacks', :action => 'assign_progress_status', via: [:get, :post]
  match '/feedbacks/other', :controller => 'feedbacks', :action => 'other', via: [:get, :post]
  # ------- Feedbacks Routes End -------

  get 'ranking/index'

  get 'notifications/index'

  get 'verifications/new'

  get 'verifications/verify'
  post 'verifications/verify'

  get 'verifications/create'
  post 'verifications/create'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  
  get '/mu-b7a80520-38574f1d-8d74f9b9-cd358b57', :to => proc { |env| [200, {}, ["42"]] }

  namespace :api, {format: 'json'} do 
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only => [:create]

    end
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: :true) do
      devise_for :users, skip: :all
      devise_scope :user do
        post "/sessions" => "sessions#create"
        post "/registrations" => "registrations#create"
        delete "/sessions" => "sessions#destroy"
      end
      resources :sessions, :only => [:create, :destroy]
      resources :registrations, :only => [:create]

      post "/verifications/create" => "verifications#create"
      post "/verifications/verify" => "verifications#verify"

      post "/feedbacks/create" => "feedbacks#create"
      post "/feedbacks/display_all" => "feedbacks#display_all"
      post "/feedbacks/display_mine" => "feedbacks#display_mine"
      post "/feedbacks/display_details" => "feedbacks#display_details"
      post "/feedbacks/create_comment" => "feedbacks#create_comment"
      post "/feedbacks/create_vote" => "feedbacks#create_vote"
      post "/feedbacks/check_vote" => "feedbacks#check_vote"
      post "/feedbacks/unvote" => "feedbacks#unvote"
      post "/feedbacks/get_comments" => "feedbacks#get_comments"
      post "/feedbacks/report_abuse" => "feedbacks#report_abuse"
      post "/feedbacks/assign_progress_status" => "feedbacks#assign_progress_status"

      post "/users/email_exists" => "users#email_exists"
      post "/users/facebook_login" => "users#facebook_login"
      post "/users/get_user" => "users#get_user"
      post "/users/change_password" => "users#change_password"
      post "/users/get_agency" => "users#get_agency"

      post "/annotations/create" => "annotations#create"

      post "/notifications/get_new_notifications" => "notifications#get_new_notifications"
      post "/notifications/get_more_notifications" => "notifications#get_more_notifications"
    end
  end

  root :to => "feedbacks#index"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :user

	has_many :comments
	has_many :votes
	has_many :notifications
	has_many :images, dependent: :destroy

	attr_accessible :title, :details, :status, :address, :latitude, :longitude, :last_acted_at, :reported_by, :abuse_reason, :abuse_status, :user_id, :created_at
	# geocoded_by :address
	# after_validation :geocode, :if => :address_changed?
	
	# reverse_geocoded_by :latitude, :longitude
	# after_validation :reverse_geocode, :if => :address_changed?

	def timestamp
  		created_at.strftime('%d %B %Y %H:%M:%S')
	end
	
end

app/controllers/api/v2/feedbacks_controller.rb
class Api::V2::FeedbacksController < FeedbacksController
skip_before_action :verify_authenticity_token
before_action :authenticate_user!, only: :trial_test
respond_to :json

	def trial_test
	end

	def display_all
		retrieve_before_time_dt = DateTime.strptime(params[:retrieve_before_time], '%Y-%m-%d %H:%M:%S')
	    feedbacks = Feedback.where("delete_status is null").where("abuse_status = ? or abuse_status = ?", "Nil", "Not Abusive").order(last_acted_at: :desc).where("last_acted_at < ?", retrieve_before_time_dt).limit(3)
	    
	    feedbacks_data = []

	    feedbacks.each do |feedback|
	    	feedback_data = Hash.new
	    	feedback_data["feedback"] = feedback
	    	feedback_data["total_votes"] = feedback.votes.count
	    	feedback_data["total_comments"] = feedback.comments.count

	    	images = feedback.images
	    	if images.size > 0
	    		image = images.first
	    		feedback_data["image"] = image
	    		feedback_data["annotations"] = image.annotations
	    	end
	    	
	    	feedbacks_data << feedback_data
	    end

		render json: { :feedbacks_data => feedbacks_data }
	end

	def display_mine
		retrieve_before_time_dt = DateTime.strptime(params[:retrieve_before_time], '%Y-%m-%d %H:%M:%S')
	    fb = Feedback.where("delete_status is null").where("abuse_status = ? or abuse_status = ?", "Nil", "Not Abusive").order(last_acted_at: :desc).where("last_acted_at < ?", retrieve_before_time_dt).limit(3)
	    if current_user.user_type == "User"
	      feedbacks = fb.where("user_id = ?", current_user.id)
	    elsif current_user.user_type == "Agency"
	      feedbacks = fb.where("handled_by = ?", current_user.id)
	    end

	    feedbacks_data = []

	    feedbacks.each do |feedback|
	    	feedback_data = Hash.new
	    	feedback_data["feedback"] = feedback
	    	feedback_data["total_votes"] = feedback.votes.count
	    	feedback_data["total_comments"] = feedback.comments.count

	    	images = feedback.images
	    	if images.size > 0
	    		image = images.first
	    		feedback_data["image"] = image
	    		feedback_data["annotations"] = image.annotations
	    	end
	    	
	    	feedbacks_data << feedback_data
	    end

		render json: { :feedbacks_data => feedbacks_data }
	end

	def display_details
		feedback = Feedback.find(params[:feedback_id])
		nickname = User.find(feedback.user_id).nickname
		total_votes = feedback.votes.count
		total_comments = feedback.comments.count

		images = feedback.images
		images_annotations = Hash.new
    	if images.size > 0
    		count = 0
    		images.each do |image|
    			key = "image_annotations_" + count.to_s
	    		image_annotations = Hash.new
	    		image_annotations["image"] = image
    			image_annotations["annotations"] = image.annotations

	    		images_annotations[key] = image_annotations
	    		count += 1
	    	end
    	end

		render json: { :feedback => feedback, :nickname => nickname, :total_votes => total_votes, :total_comments => total_comments, :images_annotations => images_annotations }
	end

	def create
		@current_user = User.find_by_authentication_token(params[:auth_token])
    	render status: 401, json: { :error => "Invalid token." } and return unless @current_user

    	@feedback = Feedback.new(feedback_params)
    	
		if @feedback.save
			@feedback.update_attribute(:last_acted_at, Time.zone.now)
			@feedback.update_attribute(:user_id, @current_user.id)
			no_of_images = 0
			no_of_annotations = 0

			# Create image models if any
			# params[:images_annotations] has the following structure: image$x_axis^y_axis^details$x_axis^y_axis^details | image
			if !params[:images_annotations].blank?
				images_annotations = params[:images_annotations].split("|")
				no_of_images = images_annotations.size

				images_annotations.each do |image_annotation|
					annotations = image_annotation.split("$")
					image_data = annotations.shift
					image = Image.new
					image.feedback_id = @feedback.id
					image.image_data = image_data

					if image.save!
						
						# Create annotation models if any
						if annotations.size > 0
							no_of_annotations += annotations.size
							
							annotations.each do |a|
								annotation_values = a.split("^")
								annotation = Annotation.new
								annotation.image_id = image.id
								annotation.x_axis = annotation_values.at(0)
								annotation.y_axis = annotation_values.at(1)
								annotation.details = annotation_values.at(2)
								
								if !annotation.save!
									@feedback.destroy
									render status: 422, json: { :error => "Failed to create feedback. Unable to save annotation(s)." }
								end
							end
						end
					else
						@feedback.destroy
						render status: 422, json: { :error => "Failed to create feedback. Unable to save image(s)." }
					end
				end
			end

			render status: 201, json: { :message => "Feedback created with " + no_of_images.to_s + " images and " + no_of_annotations.to_s + " annotations." }
		else
			render status: 422, json: { :error => "Failed to create feedback." }
		end
	end

	def create_comment
		@current_user = User.find_by_authentication_token(params[:auth_token])
    	render status: 401, json: { :error => "Invalid token." } and return unless @current_user
    	super
	end

	def create_vote
		@current_user = User.find_by_authentication_token(params[:auth_token])
    	render status: 401, json: { :error => "Invalid token." } and return unless @current_user
    	super
	end

	def get_vote
		@current_user = User.find_by_authentication_token(params[:auth_token])
    	render status: 401, json: { :error => "Invalid token." } and return unless @current_user
    	vote = Vote.where("user_id = ? AND feedback_id = ?", @current_user.id, params[:feedback_id]).take
    	return vote
    end

    def check_vote
    	if get_vote.blank?
    		render status: 200, json: { :message => "Not voted" }
    	else
    		render status: 200, json: { :message => "Voted" }
    	end
    end

	def unvote
		get_vote.destroy
		render status: 200, json: { :message => "Vote destroyed." }
	end

	def get_comments
		feedback = Feedback.find(params[:feedback_id])
		comments = feedback.comments
		comments_nicknames = []
		if !comments.blank?
			comments.each do |comment|
				nickname = User.find(comment.user_id).nickname
				comment_nickname = { "comment" => comment, "nickname" => nickname }
				comments_nicknames << comment_nickname
			end
		end
		render status: 200, json: { :comments_nicknames => comments_nicknames } 
	end

	def report_abuse
		@current_user = User.find_by_authentication_token(params[:auth_token])
    	render status: 401, json: { :error => "Invalid token." } and return unless @current_user
    	super
	end

	def assign_progress_status
		if params[:progress_status_new] == "In Progress" or params[:progress_status_new] == "Resolved"
			super
		else
			render status: 401, json: { :error => "Invalid progress status. progress_status_new can only be In Progress or Resolved" }
		end
	end

	private
		def feedback_params
		    params.permit(:title, :details, :address, :latitude, :longitude)
			# require(:feedback)
	    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :detailed_location %><br>
    <%= f.text_field :detailed_location %>
  </div>
  <div class="field">
    <%= f.label :last_acted_at %><br>
    <%= f.datetime_select :last_acted_at %>
  </div>
  <div class="field">
    <%= f.label :reported_by %><br>
    <%= f.number_field :reported_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/carousel.html.erb
<div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#carousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#carousel" data-slide="next">&rsaquo;</a>
</div>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/profile.html.erb
<br/>

<div class="container" align="center">
  <div class="row">
    <div class="panel panel-info" style="width: 40%;">

      <div class="panel-heading">
        <div class="row">
            <h3 align="center"><i class="icon-user"></i> <%= current_user.nickname%></h3>
        </div>
      </div>

      <div class="panel-body" style="margin-top: 10px;">
        <div class="row">
          <!-- class="table table-user-information" -->
          <table class="user-info">
            <tbody>
              <tr>
                <td style="width: 35%;"><b>Email:</b></td>
                <td><%= current_user.email %></td>
              </tr>
              <tr>
                <td><b>Phone Number:</b></td>
                <td><%= current_user.phone_number %></td>
              </tr>
              
              <% if current_user.user_type == "Agency" %>
                <tr>
                  <td><b>Address:</b></td>
                  <td><%= current_user.address %></td>
                </tr>
                <tr>
                  <td><b>Description:</b></td>
                  <td><%= current_user.description %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <div class="horizontal-line" style="background-color: #c4cde0; width: 95%; margin-top: -10px;"></div>
          <!-- <u><%= link_to "Click here to change password", edit_user_registration_path %></u>  -->

          <%= link_to raw("Click here to change password " '<i class=" icon-link icon-flip-horizontal"></i>'), edit_user_registration_path %>
        </div>
      </div>

    </div>
  </div>
</div>